"""Synthesis support modules. The first deep module is the ClaimClusterer
(same-claim detection), isolated specifically so it is fixture-testable: every
synthesis count depends on it (PRD stories 130-138, 157).
"""

from .clusterer import (
    DEFAULT_CANDIDATE_SIMILARITY_THRESHOLD,
    MIN_CLAIM_TEXT_LENGTH,
    AdjudicationRecord,
    AdjudicationVerdict,
    Cluster,
    ClusterResult,
    Embedder,
    ExcludedFinding,
    SameClaimAdjudicator,
    cluster_findings,
)
from .synthesizer import (
    ComputedAgreementCluster,
    ComputedDeclaredGap,
    ComputedStructure,
    ComputedTension,
    NarrationResult,
    NarrationValidationError,
    Narrator,
    RenderedEmergentGap,
    RenderedItem,
    RenderedSynthesis,
    SynthesisResult,
    TrustEncoding,
    ZeroFindingAnomaly,
    compute_structure,
    render_synthesis,
    resolve_winning_findings,
    synthesize,
    validate_narration,
)

__all__ = [
    "DEFAULT_CANDIDATE_SIMILARITY_THRESHOLD",
    "MIN_CLAIM_TEXT_LENGTH",
    "AdjudicationRecord",
    "AdjudicationVerdict",
    "Cluster",
    "ClusterResult",
    "ComputedAgreementCluster",
    "ComputedDeclaredGap",
    "ComputedStructure",
    "ComputedTension",
    "Embedder",
    "ExcludedFinding",
    "NarrationResult",
    "NarrationValidationError",
    "Narrator",
    "RenderedEmergentGap",
    "RenderedItem",
    "RenderedSynthesis",
    "SameClaimAdjudicator",
    "SynthesisResult",
    "TrustEncoding",
    "ZeroFindingAnomaly",
    "cluster_findings",
    "compute_structure",
    "render_synthesis",
    "resolve_winning_findings",
    "synthesize",
    "validate_narration",
]
